name: AthleticBuilder
version: @version@
main: xyz.acrylicstyle.athleticbuilder.AthleticBuilderPlugin
api-version: 1.13
commands:
  athletic:
    aliases: ["ath"]
    permission: athleticbuilder.athletic
